name: Trello Integration Test

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes - fixed cron syntax
  workflow_dispatch: # Optional: allows manual trigger

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: pip install requests  # Simplified - removed python-dotenv since it's not used
        
      - name: Run Trello test script
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        run: python test_card_creator.py